name: Process Evidence Folders with Plaso (psteal)

on:
  push:
    paths:
      - 'uac/**' # Monitor changes in the uac directory

jobs:
  detect-new-folders:
    runs-on: ubuntu-22.04
    outputs:
      folders: ${{ steps.get-new-folders.outputs.folders }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Identify new folders
      - name: Identify New Folders
        id: get-new-folders
        run: |
          # Fetch changes and get list of added folders
          git fetch origin
          FOLDER_PATH="uac"
          NEW_FOLDERS=$(git diff --name-status HEAD^ | grep "^A" | grep "^A\s${FOLDER_PATH}" | awk '{print $2}' | awk -F/ '{print $2}' | sort | uniq)

          echo "Newly detected folders:"
          echo "$NEW_FOLDERS"

          # Convert folder list to a comma-separated string
          FOLDERS=$(echo $NEW_FOLDERS | tr '\n' ',')
          echo "::set-output name=folders::$FOLDERS"

  process-folder:
    needs: detect-new-folders
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-new-folders.outputs.folders) }} # Each job processes one folder

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Plaso Tools
      - name: Install Plaso Tools
        run: |
          sudo apt update
          sudo apt install -y python3-plaso

      # Step 3: Run psteal.py on the assigned folder
      - name: Process Evidence with psteal
        run: |
          echo "Processing folder: ./uac/${{ matrix.folder }}"
          psteal.py --source ./uac/${{ matrix.folder }}/ -w ./inv-${{ matrix.folder }}.json -o json_line

      # Step 4: Upload the output file as an artifact
      - name: Upload psteal Output
        uses: actions/upload-artifact@v3
        with:
          name: inv-${{ matrix.folder }}
          path: inv-${{ matrix.folder }}.json
