name: Process Evidence Folders with Plaso (psteal)

on:
  push:
    paths:
      - 'uac/**' # Monitor changes in the uac directory

jobs:
  detect-new-folders:
    runs-on: ubuntu-22.04
    outputs:
      folders: ${{ steps.get-new-folders.outputs.folders }}

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history to ensure HEAD^ is available

      # Step 2: Identify new folders
      - name: Identify New Folders
        id: get-new-folders
        run: |
          git fetch origin
          FOLDER_PATH="uac"
          NEW_FOLDERS=$(git diff --name-status HEAD^ HEAD | grep "^A" | grep "^A\s${FOLDER_PATH}" | awk '{print $2}' | awk -F/ '{print $2}' | sort | uniq)

          echo "Newly detected folders:"
          echo "$NEW_FOLDERS"

          # Convert folder list to a JSON array (or an empty array if no folders are found)
          if [ -z "$NEW_FOLDERS" ]; then
            echo "[]" > folders.json
          else
            echo $NEW_FOLDERS | jq -R -s 'split("\n") | map(select(. != ""))' > folders.json
          fi

          # Set the output variable
          echo "::set-output name=folders::$(cat folders.json)"

  process-folder:
    needs: detect-new-folders
    if: needs.detect-new-folders.outputs.folders != '[]' # Skip job if no folders are detected
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-new-folders.outputs.folders) }} # Each job processes one folder

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Plaso Tools
      - name: Install Plaso Tools
        run: |
          sudo apt update
          sudo apt install -y python3-plaso

      # Step 3: Extract tar.gz files if present
      - name: Extract tar.gz Files
        run: |
          echo "Checking for tar.gz files in ./uac/${{ matrix.folder }}"
          if ls ./uac/${{ matrix.folder }}/*.tar.gz 1> /dev/null 2>&1; then
            echo "Found tar.gz files. Extracting..."
            for archive in ./uac/${{ matrix.folder }}/*.tar.gz; do
              echo "Extracting $archive"
              tar -xzf "$archive" -C ./uac/${{ matrix.folder }}
            done
          else
            echo "No tar.gz files found in ./uac/${{ matrix.folder }}"
          fi

      # Step 4: Run psteal.py on the assigned folder
      - name: Process Evidence with psteal
        run: |
          echo "Processing folder: ./uac/${{ matrix.folder }}"
          psteal.py --source ./uac/${{ matrix.folder }}/ -w ./inv-${{ matrix.folder }}.json -o json_line

      # Step 5: Upload the output file as an artifact
      - name: Upload psteal Output
        uses: actions/upload-artifact@v3
        with:
          name: inv-${{ matrix.folder }}
          path: inv-${{ matrix.folder }}.json
